#!/usr/bin/env python3
"""Per-CV deep analysis for the validation report.

For every PDF in the supplied directory (skipping a configurable list of
synthetic test fixtures) this script:

  1. Reads file metadata (size, page count, producer) via PyMuPDF.
  2. Runs each extractor independently (pdfplumber, PyMuPDF, OCR).
  3. Runs the cascading ExtractionPipeline.
  4. Performs the qualitative checks the validation task requires:
       - first 500 chars / last 300 chars of pipeline text
       - diacritics present?
       - common CV section headers present?
       - email & phone-like patterns preserved?
       - per-page multi-column flags
  5. Dumps everything to a single JSON file.

Designed to be re-runnable.  It does NOT mutate the fixtures.
"""

import argparse
import json
import re
import sys
import time
from pathlib import Path
from typing import Any

# Force UTF-8 stdout/stderr so we can print filenames containing non-cp1252
# characters (e.g. Romanian "ț") on Windows consoles without crashing.
for _stream in (sys.stdout, sys.stderr):
    reconfigure = getattr(_stream, "reconfigure", None)
    if callable(reconfigure):
        reconfigure(encoding="utf-8", errors="replace")

sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from cv_extractor.config import ExtractorConfig  # noqa: E402
from cv_extractor.exceptions import CVExtractorError  # noqa: E402
from cv_extractor.extractors.ocr_extractor import OCRExtractor  # noqa: E402
from cv_extractor.extractors.pdfplumber_extractor import PdfPlumberExtractor  # noqa: E402
from cv_extractor.extractors.pymupdf_extractor import PyMuPDFExtractor  # noqa: E402
from cv_extractor.pipeline import ExtractionPipeline  # noqa: E402
from cv_extractor.postprocess import postprocess_text  # noqa: E402

# Default fixtures generated by tests/conftest.py — not part of the real
# validation set but they live in the same directory.
DEFAULT_EXCLUDE = {
    "single_column.pdf",
    "two_column.pdf",
    "minimal.pdf",
    "corrupt.pdf",
}

DIACRITICS = "ăâîșțĂÂÎȘȚ"
SECTION_HEADERS = [
    "experience", "education", "skills", "projects", "certifications",
    "experiență", "educație", "competențe", "proiecte", "certificări",
]
EMAIL_RE = re.compile(r"\S+@\S+\.\S+")
# Phone heuristic: 7+ digits with optional separators
PHONE_RE = re.compile(r"(?:\+?\d[\d\s().-]{6,}\d)")


def _file_metadata(pdf_path: Path) -> dict[str, Any]:
    import pymupdf  # type: ignore[import-not-found]

    out: dict[str, Any] = {
        "filename": pdf_path.name,
        "size_bytes": pdf_path.stat().st_size,
        "page_count": None,
        "producer": None,
        "creator": None,
        "title": None,
    }
    try:
        with pymupdf.open(str(pdf_path)) as doc:
            out["page_count"] = doc.page_count
            md = doc.metadata or {}
            out["producer"] = md.get("producer")
            out["creator"] = md.get("creator")
            out["title"] = md.get("title")
    except Exception as exc:  # pragma: no cover
        out["metadata_error"] = str(exc)
    return out


def _run_extractor(extractor: Any, pdf_path: Path) -> dict[str, Any]:
    """Run a single extractor and return chars/words/time/error/text."""
    start = time.monotonic()
    try:
        raw = extractor.extract(pdf_path)
        text = postprocess_text(raw.text, was_ocr=(extractor.name == "ocr_tesseract"))
        elapsed_ms = int((time.monotonic() - start) * 1000)
        return {
            "succeeded": True,
            "chars": len(text),
            "words": len(text.split()),
            "time_ms": elapsed_ms,
            "error": None,
            "text": text,
        }
    except CVExtractorError as exc:
        elapsed_ms = int((time.monotonic() - start) * 1000)
        return {
            "succeeded": False,
            "chars": 0,
            "words": 0,
            "time_ms": elapsed_ms,
            "error": f"{type(exc).__name__}: {exc}",
            "text": "",
        }
    except Exception as exc:
        elapsed_ms = int((time.monotonic() - start) * 1000)
        return {
            "succeeded": False,
            "chars": 0,
            "words": 0,
            "time_ms": elapsed_ms,
            "error": f"Unexpected: {type(exc).__name__}: {exc}",
            "text": "",
        }


def _qualitative_checks(text: str) -> dict[str, Any]:
    lower = text.lower()
    diacritics_found = sorted({c for c in text if c in DIACRITICS})
    section_hits = [h for h in SECTION_HEADERS if h in lower]
    emails = EMAIL_RE.findall(text)
    phones = PHONE_RE.findall(text)
    # Garbage-character check: any character outside printable + common
    # latin-extended ranges.
    weird = [c for c in text if ord(c) < 32 and c not in "\n\r\t"]
    return {
        "diacritics_found": diacritics_found,
        "diacritics_present": bool(diacritics_found),
        "section_headers_found": section_hits,
        "emails_found": emails[:5],
        "phones_found": phones[:5],
        "weird_control_chars": len(weird),
        "first_500": text[:500],
        "last_300": text[-300:] if len(text) > 300 else text,
    }


def analyse(pdf_path: Path, config: ExtractorConfig) -> dict[str, Any]:
    out: dict[str, Any] = {"file": _file_metadata(pdf_path)}

    extractors = {
        "pdfplumber": PdfPlumberExtractor(config),
        "pymupdf": PyMuPDFExtractor(config),
        "ocr_tesseract": OCRExtractor(config),
    }
    extractor_results: dict[str, Any] = {}
    for name, ext in extractors.items():
        res = _run_extractor(ext, pdf_path)
        # Strip the full text out of the per-extractor record to keep the JSON
        # readable — keep only first/last samples.
        text = res.pop("text")
        if text:
            res["first_300"] = text[:300]
            res["last_200"] = text[-200:] if len(text) > 200 else text
        extractor_results[name] = res
    out["extractors"] = extractor_results

    # Pipeline (cascading orchestrator)
    pipeline = ExtractionPipeline(config=config, raise_on_low_quality=False)
    pipe_start = time.monotonic()
    try:
        result = pipeline.process(pdf_path)
        pipe_elapsed = int((time.monotonic() - pipe_start) * 1000)
        meta = result.metadata
        out["pipeline"] = {
            "succeeded": True,
            "method_used": meta.method_used.value,
            "total_pages": meta.total_pages,
            "processing_time_ms": meta.processing_time_ms,
            "wall_clock_ms": pipe_elapsed,
            "quality_score": meta.quality_score,
            "detected_language": meta.detected_language,
            "is_scanned": meta.is_scanned,
            "warnings": result.warnings,
            "chars": len(result.text),
            "words": len(result.text.split()),
            "page_multi_column_flags": [p.is_multi_column for p in meta.pages],
            "page_word_counts": [p.word_count for p in meta.pages],
            "qualitative": _qualitative_checks(result.text),
        }
    except CVExtractorError as exc:
        out["pipeline"] = {
            "succeeded": False,
            "error": f"{type(exc).__name__}: {exc}",
            "wall_clock_ms": int((time.monotonic() - pipe_start) * 1000),
        }
    except Exception as exc:
        out["pipeline"] = {
            "succeeded": False,
            "error": f"Unexpected: {type(exc).__name__}: {exc}",
            "wall_clock_ms": int((time.monotonic() - pipe_start) * 1000),
        }
    return out


def main() -> None:
    parser = argparse.ArgumentParser(description="Per-CV deep analysis dumper")
    parser.add_argument("pdf_dir", type=Path)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument(
        "--exclude",
        nargs="*",
        default=sorted(DEFAULT_EXCLUDE),
        help="Filenames to skip (defaults to synthetic conftest fixtures).",
    )
    args = parser.parse_args()

    pdfs = sorted(p for p in args.pdf_dir.glob("*.pdf") if p.name not in set(args.exclude))
    if not pdfs:
        print(f"No PDFs found in {args.pdf_dir} after exclusions", file=sys.stderr)
        sys.exit(1)

    print(f"Per-CV deep analysis on {len(pdfs)} CV(s):")
    for p in pdfs:
        print(f"  - {p.name}")

    # Deliberately permissive config so the pipeline never hard-fails on the
    # real CVs and we capture full metadata even on borderline files.
    config = ExtractorConfig(min_quality_score=0.05)

    per_cv: list[dict[str, Any]] = []
    for i, pdf in enumerate(pdfs, start=1):
        print(f"[{i}/{len(pdfs)}] {pdf.name}")
        per_cv.append(analyse(pdf, config))

    args.output.parent.mkdir(parents=True, exist_ok=True)
    with args.output.open("w", encoding="utf-8") as f:
        json.dump({"cvs": per_cv}, f, indent=2, ensure_ascii=False)
    print(f"\nWrote {args.output}")


if __name__ == "__main__":
    main()
